---
# The supplier will bind with this account on the consumer, so the account should exist on the consumer
- name: Add "supplier bind DN entry" to consumer
  ldap_entry:
    server_uri: "{{ dirsrv_server_uri }}"
    validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
    start_tls: "{{ dirsrv_use_starttls }}"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn={{ dirsrv_replication_user }},cn=config"
    objectClass:
      - top
      - device
      - simpleSecurityObject
    attributes:
      cn: "{{ dirsrv_replication_user }}"
      userPassword: "{{ dirsrv_replication_user_password }}"
      nsIdleTimeout: 0  # TODO: make this configurable? 0 is only needed for initialization, since it may take a long time
    state: present

# Allows password change, since if entry exists, ldap_entry doesn't update attributes
- name: Set "supplier bind DN entry" attributes
  ldap_attrs:
    server_uri: "{{ dirsrv_server_uri }}"
    validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
    start_tls: "{{ dirsrv_use_starttls }}"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn={{ dirsrv_replication_user }},cn=config"
    state: exact
    attributes:
      userPassword: "{{ dirsrv_replication_user_password }}"
  changed_when: false  # Password always changes, but doesn't really change
