---
- name: Create Supplier Replica Entry
  ldap_entry:
    server_uri: "{{ dirsrv_server_uri }}"
    validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
    start_tls: "{{ dirsrv_use_starttls }}"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn=replica,cn=\"{{ dirsrv_suffix }}\",cn=mapping tree,cn=config"
    objectClass:
      - top
      - nsds5replica
      - extensibleObject
    attributes:
      cn: "replica"
      # MUST attributes, cannot add them later
      nsds5replicaroot: "{{ dirsrv_suffix }}"
      nsds5replicaid: "{{ dirsrv_supplier_replica_id }}"
      nsds5replicatype: "3"  # Cannot be changed later
    state: present

- name: Configure Supplier Replica Entry
  ldap_attrs:
    server_uri: "{{ dirsrv_server_uri }}"
    validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
    start_tls: "{{ dirsrv_use_starttls }}"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn=replica,cn=\"{{ dirsrv_suffix }}\",cn=mapping tree,cn=config"
    state: exact
    attributes:
      nsds5replicaroot: "{{ dirsrv_suffix }}"
      nsds5ReplicaBindDN: "cn={{ dirsrv_replication_user }},cn=config"
      nsds5flags: "1"  # 1 = writes to changelog = is a supplier (use 0 for consumers)
      nsds5replicaid: "{{ dirsrv_supplier_replica_id }}"
      # This is already the default: keep "tombstone" for deleted entries for 1 week, to resolve conflicts in master-master replication
      # nsds5ReplicaPurgeDelay  : "604800"
